export ZSH_COMPDUMP="$HOME/.cache/zsh/zcompdump"
export PATH=/usr/local/bin:$PATH
export EDITOR='vim'

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

#ACTIVATE SHORTCUTS
source $HOME/.config/shell/aliasrc
